### PR TITLE
use the right capitalization for the SHA keyword argument

### PR DESCRIPTION
**Pull request by tkelman**

### CODE REVIEW

**Comment by tkelman** [comment]
Travis is MIA here...

**Comment by malmaud** [comment]
You'd love for me to merge this, wouldn't you?

**Comment by tkelman** [comment]
There is something wrong with the binaries: https://ci.appveyor.com/project/malmaud/mbedtls-jl-qfj9w/build/1.0.68/job/d2s4fvg9qkgnn30d

**Comment by malmaud** [comment]
I think there is just something wrong with the version verifier logic on
Windows, as the tests passed.

**Comment by tkelman** [comment]
`could not load symbol \"mbedtls_version_get_string\"\nThe specified procedure could not be found.`

Bug me again over the next few weeks to take a closer look. When you update to the latest version you'll need to rebuild anyway, probably worth putting on winrpm anyway.

**Pull request merged**
