### PR TITLE
Fix mbedtls_pk native method calls

### LINKED ISSUE #33: LoadError: ccall: could not find function mbedtls_pk_init in library libmbedtls.DLL
I was executing ```Pkg.test("HttpServer")``` and encountered following error

```
julia> Pkg.test("HttpServer")
INFO: Computing test dependencies for HttpServer...
INFO: Installing Requests v0.3.5
INFO: Building HttpParser
INFO: Building MbedTLS
WARNING: Could not check MbedTLS version
WARNING: Could not check MbedTLS version
WARNING: Could not check MbedTLS version
WARNING: Could not check MbedTLS version
INFO: Testing HttpServer
INFO: Recompiling stale cache file C:\Users\Administrator\.julia\lib\v0.4\HttpParser.ji for module HttpParser.
INFO: Recompiling stale cache file C:\Users\Administrator\.julia\lib\v0.4\HttpServer.ji for module HttpServer.
INFO: Recompiling stale cache file C:\Users\Administrator\.julia\lib\v0.4\MbedTLS.ji for module MbedTLS.
HttpServer utility functions:
  > `write` correctly writes data response
5 facts verified.
INFO: Recompiling stale cache file C:\Users\Administrator\.julia\lib\v0.4\Requests.ji for module Requests.
HttpServer runs
  > using HTTP protocol on 0.0.0.0:8000
Listening on 0.0.0.0:8000...
  > using HTTP protocol on 127.0.0.1:8001
Listening on 127.0.0.1:8001...
  > Testing HTTPS on port 8002
ERROR: LoadError: ccall: could not find function mbedtls_pk_init in library C:\Users\Administrator\.julia\v0.4\MbedTLS\deps\usr\bin64\libmbedtls.DLL
 in call at C:\Users\Administrator\.julia\v0.4\MbedTLS\src\pk.jl:8
while loading C:\Users\Administrator\.julia\v0.4\HttpServer\test\runtests.jl, in
 expression starting on line 25
=============================[ ERROR: HttpServer ]==============================


failed process: Process(`'C:\Users\Administrator\AppData\Local\Julia-0.4.3\bin\julia' --check-bounds=yes --code-coverage=none --color=yes 'C:\Users\Administrator\.julia\v0.4\HttpServer\test\runtests.jl'`, ProcessExited(1)) [1]

================================================================================

INFO: Removing Requests v0.3.5
ERROR: HttpServer had test errors
 in error at error.jl:21
```

The error seems to be from MbedTLS package, the package was unable to find ```mbedtls_pk_init``` function in libmbedtls.DLL . when I cross checked  ```libmbedtls.DLL``` was located in following path ```C:\Users\Administrator\.julia\v0.4\MbedTLS\deps\usr\bin64\libmbedtls.DLL``` , maybe the version of DLL is wrong ? 

I encountered this error on following configuration 

```
OS = Windows 2008 server R2 Service Pack 1
Julia version = 0.4.3
MbedTLS.jl version = 0.2.1
HttpServer version = v"0.1.5"
```

I was able to reproduce this error on following configuration too
```
OS = Windows 10
Julia version = 0.4.3
MbedTLS.jl version = v"0.2.0"
HttpServer version = v"0.1.5"
```

### PR DESCRIPTION
**Pull request by Distjubo**
(Hopefully) fixes #33

### CODE REVIEW

**Comment by Distjubo** [comment]
Do note that I have only tested this on my Windows 10 machine.

**Comment by malmaud** [comment]
Thanks! Would you mind adding a test?

**Comment by Distjubo** [comment]
Sorry, I'm pretty new to julia. I mean I can give it a shot, but I really have no idea how that test should look like. Should I simply read a sample key and verify that it loaded? Or do I somehow have to verify the correctness of that key, and if so, how?

**Comment by malmaud** [comment]
The former is fine for now - anything that just exercises the code path of
the key-loading logic.

**Comment by Distjubo** [comment]
I need a little bit of help: I'm working on that test, but I have no idea how to generate a key file. In a test for some private code I'm generating a key with a somewhat tedious command: 

> run(pipeline(`openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout "test/sslkey/server.key" -out "test/sslkey/server.crt"`,
>                    stdin=`cmd /c echo DE&&echo Rheinland Pfalz&&echo Gensingen&&echo.&&echo.&&echo.&&echo distjubo@gmail.com`))

But I guess that doesn't work on linux or other platforms. Help greatly appreciated :baby_bottle:

**Comment by Distjubo** [comment]
Okay I've done some tests, which (with my special key generation stuff) work on my machine. I haven't added that cheesy echo method to pipe my credentials into openssl to the tests though, I've copied the key generation from the HttpServer tests. But for the other stuff you'll have to look into how to test that, I have simply no idea how to use those methods. Those methods are:

- decrypt!
- encrypt!
- parse_key!
- parse_public_keyfile

**Comment by Distjubo** [comment]
Well, as you can see, the key generation stuff used in HttpServer.jl doesn't really work and the build failed.

**Comment by Distjubo** [comment]
I also forgot to push one of the local changes, sorry.

**Comment by Distjubo** [comment]
I don't want to seem impatient, but I actually am. Sorry. If you could tell me what to do about the openssl problem that would be great.

**Comment by malmaud** [comment]
I was planning on looking into this today.

**Comment by Distjubo** [comment]
Ok great :+1:

**Comment by malmaud** [comment]
The test has to be changed slightly, but this is basically correct. I'll merge it and then commit a revised test.

**Comment by Distjubo** [comment]
One thing you could also do is make the get_name check case insensitive, I mean lowercase rsa would also be correct right?

**Pull request merged**
