### PR TITLE
More adjustments for IO refactoring

### PR DESCRIPTION
**Pull request by ihnorton**
...

### CODE REVIEW

**Comment by malmaud** [comment]
Thanks!

**Comment by malmaud** [comment]
Oh actually, we should decide if we're maintaining .4 compatibility on master before merging this.

**Comment by tkelman** [comment]
I'm reasonably sure this package is going to need 0.4-compatible bugfix releases. Unless fixing it on master is really urgent, I think getting https://github.com/JuliaLang/Compat.jl/pull/162 into shape and seeing if that can be used here is a better option.

**Comment by malmaud** [comment]
Makes sense

**Pull request merged**
